### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by danparn** [loginov-rocks/bluetooth-terminal#66]
There is an undefined **navigator** object at line 278. You create it as global in the test procedure, but without this hack, the library cannot be used, unfortunately.

**Comment by loginov-rocks** [comment]
> There is an undefined **navigator** object at line 278. You create it as global in the test procedure, but without this hack, the library cannot be used, unfortunately.

Hi @danparn ,

You probably use some very outdated browser: https://caniuse.com/mdn-api_navigator
