### ISSUE TITLE
Error When Connecting with My Phone

### ISSUE THREAD

**Issue by iamgabrielsoft** [loginov-rocks/bluetooth-terminal#68]
I get Network error when connecting with my Phone. How do I resolve this?

**Comment by loginov-rocks** [comment]
Hi @iamgabrielsoft , any details, logs?

**Comment by iamgabrielsoft** [comment]
Sorry loginov-rocks for the late reply

**Comment by iamgabrielsoft** [comment]
I did try connecting with my Laptop, I I received an error while trying to connect..

**Comment by loginov-rocks** [comment]
What browser did you use? Those are supported: https://caniuse.com/web-bluetooth
